# Generated by Django 3.0.3 on 2022-05-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0004_taxonomy_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='sequence',
            field=models.CharField(max_length=256),
        ),
    ]
