# Generated by Django 3.0.3 on 2022-05-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0007_auto_20220507_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='pfam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfamid_in_domains', to='genedata.Pfam'),
        ),
        migrations.AlterField(
            model_name='domains',
            name='protein_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteinid_in_domains', to='genedata.Protein'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxa_in_protein', to='genedata.Taxonomy'),
        ),
    ]
