# Generated by Django 3.0.3 on 2022-05-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0008_auto_20220508_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='protein_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='genedata.Protein'),
        ),
    ]
