# Generated by Django 3.0.3 on 2022-05-09 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0009_auto_20220508_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy_protein',
            name='taxa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxonomy_protein', to='genedata.Taxonomy'),
        ),
    ]
