# Generated by Django 3.0.3 on 2022-05-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0013_auto_20220513_0508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxonomy_Domain',
            new_name='Taxonomy_Pfam',
        ),
    ]
